### PR TITLE
Update background.coffee

### PR DESCRIPTION
**Pull request by xxcctthi**
Improve readability of `getIsActive` function. Change equality operators to `===`

### CODE REVIEW

**Comment by imdreamrunner** [comment]
Thanks for your pull request.

`!==` and `===` is not supported by coffee-script. `==` will be translated into `===` by coffee compiler.

You may refer to the build result [here](https://travis-ci.org/imdreamrunner/WatchOnYouTube/builds/58759508)

**Comment by xxcctthi** [comment]
Aaahhh, okay. My thinking is still with the plain vanilla JS.

**Comment by imdreamrunner** [comment]
hello miao

**Comment by xxcctthi** [comment]
miao :octocat: miao :octocat:

**Pull request closed without merging**
